### ISSUE TITLE
Testy jednostkowe dla pluginów

### ISSUE THREAD

**Issue by annaskulimowska** [kmisztal/KiMage#13]
Działanie pluginów powinno być przetestowane testami jednostkowymi.

**Comment by dkrawiec** [comment]
zbyt ogólny task. Ja bym to zrealizował przy okazji/po wydzieleniu modułów dla pluginów

**Comment by annaskulimowska** [comment]
nie jest ready to implement, to nie jest na teraz. Można w nim wylistować listę pluginów do przetestowania. Pamiętaj, że pracujemy w grupie i inne osoby będą pracować przy tym projekcie niezależnie od nas. Dodatkowo piszę o testach jednostkowych, a nie integracyjnych.

**Comment by dkrawiec** [comment]
Ok, czyli rozumiem że docelowo rozdzielamy taski per plugin?

**Comment by annaskulimowska** [comment]
chciałam uniknąć dużej ilości tasków, ale może tak faktycznie byłoby lepiej. Każdy ma wtedy swoje "poletko" do działania. Zobaczmy może co wyjdzie przy implementacji pierwszej integracji pluginów z event busem

**Comment by kmisztal** [comment]
pluginy można podzielić na co najmniej trzy rodzaje:
A: bezkontekstowe - działają na pojedynczym pikselu;
B: kontekstowe - działają na piskselu wykorzystując informacje o jego sąsiadach;
C: bardziej skomplikowane, często zawierają pluginy z poprzednich punktów.

myślę, że na początek trzeba zająć się przykładami z A i B, potencjalnie łatwo tutaj też o zrównoleglenie (jeśli potrzebne)

taski per plugin? w części z A i B da się pogrupować na kilka tego samego rodzaju

**Comment by kmisztal** [comment]
p.s. nie wiem jak to wyjdzie w ogólności, ale jakby co to można zrobić kilka przykładowych pluginów aby pokazać jak to ma działać a resztę zostawić - wszystko zależy od tego jak będzie z czasem, co o tym sądzicie?

**Comment by annaskulimowska** [comment]
zgadzam się z tym, że trzeba zacząć od prostego pluginu, po drodze wyjdą pewnie jeszcze sprawy których nie przewidzieliśmy

**Comment by dkrawiec** [comment]
Is it still a valid issue? Test should be a requirement of a story dedicated to a specific plugin. @annadobrowolska  can you close it?
