### ISSUE TITLE
Move current code in image-processor module to legacy package

### ISSUE THREAD

**Issue by annaskulimowska** [kmisztal/KiMage#19]
Move current code in image-processor module to legacy package. A new code cannot import anything from this package.

**Comment by dkrawiec** [comment]
How is it going? Maybe I'll help you :8ball:

**Comment by annaskulimowska** [comment]
A few days ago I sent message to you (via Slack) and you didn"t answer. Now I am on a vacation, so this task wilk be done in the next week.

-----Wiadomość oryginalna-----
Od: "dkrawiec" notifications@github.com
Wysłano: ‎2016-‎04-‎09 10:09
Do: "kmisztal/KiMage" KiMage@noreply.github.com
DW: "annadobrowolska" anna90dobrowolska@gmail.com
Temat: Re: [kmisztal/KiMage] Move current code in image-processor module tolegacy package (#19)

How is it going? Maybe I'll help you

**Comment by dkrawiec** [comment]
Strange, I didn't receive any message. Ok so I will take care of that.

**Comment by annaskulimowska** [comment]
Please do not modify issues assigned to me. 

-----Wiadomość oryginalna-----
Od: "Damian Krawiec" notifications@github.com
Wysłano: ‎2016-‎04-‎09 10:39
Do: "kmisztal/KiMage" KiMage@noreply.github.com
DW: "annadobrowolska" anna90dobrowolska@gmail.com
Temat: Re: [kmisztal/KiMage] Move current code in image-processor module tolegacy package (#19)

Strange, I didn't receive any message. Ok so I will take care of that.

**Comment by dkrawiec** [comment]
Sure. This needs to be done and we don't have much time, so I proceeded with the changes. Could you review the change set?

**Comment by annaskulimowska** [comment]
Ok, but this shouldn't go that way. It is important that everybody can done assigned issues. 

I can't before thursday, I write from my phone.

-----Wiadomość oryginalna-----
Od: "Damian Krawiec" notifications@github.com
Wysłano: ‎2016-‎04-‎09 14:40
Do: "kmisztal/KiMage" KiMage@noreply.github.com
DW: "annadobrowolska" anna90dobrowolska@gmail.com
Temat: Re: [kmisztal/KiMage] Move current code in image-processor module tolegacy package (#19)

Sure. This needs to be done and we don't have much time, so I proceeded with the changes. Could you review the change set?

**Comment by dkrawiec** [comment]
I fully understand that, but this is a critical change before anything can be done. Next weekend I won't have any time to work on the project so I want to do as much as I can this weekend. Therefore I unassigned you, and implemented it myself.
