### ISSUE TITLE
Skonkretyzowanie wyrzucanych wyjątków

### ISSUE THREAD

**Issue by annaskulimowska** [kmisztal/KiMage#4]
Wyrzucane wyjątki typu RuntimeException, Exception, Throwable powinny być zmienione na konkretniejsze podklasy np. IllegalArgumentException, IllegalStateException. Do treści wyrzucanych wyjątków powinno być dołączone maksimum informacji, które mogą pomóc w odnalezieniu przyczyny. Przykładowo jeśli plik nie zostanie odnaleziony treść wiadomości powinna zawierać nazwę/ścieżkę pliku.

**Comment by dkrawiec** [comment]
Is it still a valid issue? This relates to a legacy code which should be either moved or removed. Story aimed for a specific plugin should state what exceptionscan it throw and how to handle this (for now we don't have a mechanism for notifying errors to gui, should we have one?)

**Comment by annaskulimowska** [comment]
this issue could be removed, for now we don't have time for error handling, but for the future it is great idea

**Comment by dkrawiec** [comment]
So please close.
