### ISSUE TITLE
Wskazówki dla developerów

### ISSUE THREAD

**Issue by annaskulimowska** [kmisztal/KiMage#9]
W Wiki lub w pliku CONTRIBUTING.md powinny znaleźć się wskazówki / ogólne zalecenia dla deweloperów:

**Projekt:**
- używamy domyślnego formattera ze środowiska IntelliJ. Niedopuszczalne jest commitowanie innego formatowania. Przykładowo zbędnych pustych linii, klamer w niestandardowych miejscach, zawijania w inny sposób importów do \* itp. Przed pushem należy upewnić się, że środowisko nie zmieniło formatowania,
- nazwy commitów rozpoczynamy od numeru zgłoszenia na GitHubie np. `#9 Add CONTRIBUTING.md file to tell users how they can contribute`. Nie modyfikujemy kodu bez odpowiedniego zgłoszenia na GitHubie,
- projekt po akceptacji zmian w kodzie musi się kompilować i muszą przechodzić wszystkie testy,
- osoba zatwierdzająca zmiany w kodzie powinna przeprowadzić na nim code review,
- nie commitujemy zakomentowanego kodu,
- zadania wykonujemy wtedy, kiedy są do nas przypisane,
- commity powinny być atomowe. Jeden commit odpowiada za jedną, konkretną zmianę która powinna być opisana w treści commita. Wszelkiego rodzaju spójniki najczęściej oznaczają, że commit powinien zostać rozbity na większą ilość commitów,
- treść commita powinna dokładnie opisywać co zostało zmienione w tym commicie. Jeśli commit zawiera zmiany nieopisane w treści commita to osoba wykonująca code review powinna odrzucić pull request

**Kod:**
- dokumentacja kodu jest wymagana tylko przy interfejsach oraz przy pustych blokach kodu. Przykładowo klasa narzędziowa zawierająca tylko statyczne metody powinna mieć prywatny konstruktor, który zawiera komentarz, że jest to klasa narzędziowa. Nie należy dodawać komentarzy w oczywistych miejscach. Komentarze nie powinny tłumaczyć co robi kod - to wie programista. Komentarze mogą wyjaśniać powody wyboru konkretnego rozwiązania.
- niedopuszczalne są nieodpowiednie nazwy zmiennych / klas / metod. Nazwa musi spełniać konwencje używane w języku Java. Nie może być jednoliterowa z wyjątkiem bardzo krótkich metod i liczników w pętlach które są nieskomplikowane,
- kod powinien być pisany w sposób bezpieczny dla wątków, projekt docelowo będzie miał możliwość uruchamia na wielu maszynach,
- przed dodaniem nowych bibliotek konieczna jest konsultacja z zespołem kontrybutorów np. poprzez odpowiednie zgłoszenie w GitHubie,
- kod powinien być przejrzysty, zgodny z ogólnymi zasadami clean code,
- testy jednostkowe powinny pokrywać maksymalną możliwą ilość kodu. Dane testowe powinny być wyznaczane z należytą uwagą, koniecznie uwzględniając wartości brzegowe,
- nie wyrzucamy ogólnych wyjątków typu Exception, Throwable, RuntimeException,
- do wyjątków zawsze dodajemy treść wskazującą źródło problemu oraz dodatkowe dane np. ścieżki do pliku którego nie znaleziono,
- zamiast korzystać z `null` korzystamy z `Optional`
- kod piszemy używając języka angielskiego, dotyczy to również komentarzy umieszczanych w kodzie, ustawień itp

**Comment by dkrawiec** [comment]
Jeżeli już jesteśmy przy wskazówkach, to jakim językiem powinniśmy się posługiwać przy opisie commitów?

**Comment by annaskulimowska** [comment]
to samo pytanie do code review, komentarzy na GitHubie

**Comment by kmisztal** [comment]
opisy commitów - angielski
co do code review to było by miło po angielsku, jeśli się nie da po polsku

**Comment by annaskulimowska** [comment]
komentarze na GitHubie w każdym miejscu można pisać w dowolnym języku, to tylko nasze ustalenia :smile:

**Comment by dkrawiec** [comment]
To jeszcze jedna uwaga ode mnie. Nie korzystamy z mocków w testach jednostkowych, chyba że jest to absolutnie jedyna możliwość przetestowania kodu który zależy od czegoś na zewnątrz. W innym wypadku poprawiamy testowany kod (i nie chodzi tu o zwykłą zamianę z private na public)

**Comment by annaskulimowska** [comment]
sądzę, że lepiej jest nie wpisywać mocków. To są zasady których wszyscy muszą się trzymać, nie ma sytuacji wyjątkowych. Jeśli ktoś bardzo potrzebuje mocków to nie widzę przeciwwskazań, generalnie mockowanie zachowania metod zamiast np. zwracania mocków jest przecież ok. To jest dyskusyjny temat i sądzę, że lepszym miejscem na to jest code review

**Comment by dkrawiec** [comment]
Przeciwwskazania są bardzo proste. Utrzymanie projektu. Ktoś kto pisze mocki ma gdzieś pracę którą będzie musiał wykonać ktoś aby dostosować mocki do zmian w przyszłości. Pomijając że jeżeli musimy np mockować model, to znaczy że coś mamy krzywo w modelu... Tego jest więcej.

To jak wyglądają dobrze napisane mocki jest sprawą dość dyskusyjną, więc z defaulta bym mocki zbanował, o ile nie ma innego wyjścia (bo problem jest na zewnątrz).

**Comment by annaskulimowska** [comment]
w tym rzecz, to jest dyskusyjne, a od dyskusji jest review
